const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
const menu = $('#menu-panel');
function closeMenu(){menu.hidden=true;$('.menu-button').setAttribute('aria-expanded','false');$('.menu-icon').textContent='＋';document.body.classList.remove('menu-open');}
$('.menu-button').addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;$('.menu-button').setAttribute('aria-expanded',String(open));$('.menu-icon').textContent=open?'−':'＋';document.body.classList.toggle('menu-open',open);});
$$('#menu-panel a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),2500);}
async function copy(text,success){try{await navigator.clipboard.writeText(text);toast(success);}catch{toast('请长按或选中文字复制');}}
$('#copy-email').addEventListener('click',()=>copy('ziming-Huang@outlook.com','邮箱已复制'));
const projects={
 skills:{title:'AI 安全 Skill 体系',tag:'01 / AGENT ENGINEERING · 2025 — PRESENT',intro:'围绕安全数字员工，主导误报标记、漏洞修复及安全编码三大核心 Skill 的开发与迭代，推动多个使用端的能力对齐。',metrics:[['3','核心 Skill'],['4','使用端覆盖'],['<10k','安全编码规则上下文 Tokens']],sections:[['问题','安全能力分散在扫描、审计与修复环节。不同使用端的调用方式和上下文组织存在差异，需要把这些能力连接为可以持续使用的工作流程。'],['我的工作',['主导误报标记、漏洞修复与安全编码 Skill 的开发、迭代和验证。','基于 Cisco Codeguard 二次开发安全编码 Skill，完成规则清洗与上下文压缩。','适配 Python、C++、Java，推进本地 CLI、云端、Space 与 IDE 插件端的功能对齐。','优化 AGENT.md，处理错误调用问题，完善从扫描到预防的工作闭环。']],['如何验证','通过多语言、多端功能验证与生产运营分析，检查调用正确性、规则适配和交付一致性；材料中记录安全编码能力已通过三端验收测试。'],['交付结果','形成误报标记、漏洞修复、安全编码三类核心 Skill，覆盖四端使用场景。安全编码规则上下文压缩至 10k Tokens 以下。']],note:'范围说明：四端覆盖与三端验收为不同口径，不能等同为所有能力均已通过四端验收。内部实现与生产材料不在此公开。'},
 detection:{title:'恶意域名与 IP 检测 Agent',tag:'02 / THREAT INTELLIGENCE · 2025',intro:'独立开发并部署基于 AI Agent 的恶意域名与 IP 检测系统，将信息收集、分析判断与结果输出串联，提升实际工作场景中的分析效率。',metrics:[['2 min','原平均分析时间'],['<10 sec','优化后平均分析时间'],['>95%','材料记录的准确率']],sections:[['问题','威胁情报研判需要整合多个线索，并在有限时间内形成可用结论。重复的信息整理与分析步骤影响响应速度。'],['我的工作',['独立完成 AI Agent 检测系统开发与部署。','将恶意域名、IP 的检测分析串成自动化流程，服务实际工作场景。','参与真实攻击流量 PCAP 分析，提取攻击载荷特征并编写 Suricata 规则。']],['研究延伸','硕士阶段以第一作者完成《A Two-Stage Hybrid Framework for DGA Detection Combining LLM with Random Forest Model》，获 CCNS 2025 录用。论文与检测系统分别作为研究和工程成果展示。'],['结果与边界','个人经历材料记录：平均分析时间从 2 分钟降至 10 秒以下，准确率达到 95% 以上。这些数据来自该项目的实际工作场景，不能直接外推至所有威胁类型。']],note:'指标来源：个人经历材料。公开资料未提供测试样本量、类别分布与完整统计口径，因此此处不作跨工具性能排名。'},
 evaluation:{title:'SAST 与代码审计效能评估',tag:'03 / RESEARCH & EVALUATION · 2025 — PRESENT',intro:'建立 AI 降噪评测与运营分析机制，通过多模型、多工具对比，为模型选型和代码审计智能体迭代提供依据。',metrics:[['多模型','对标与灰度评测'],['多工具','SAST 能力比较'],['持续','生产运营分析']],sections:[['问题','一次审计输出看似合理，并不意味着判断成立。需要同时关注误报、漏报、性能和实际使用条件，才能判断工具是否真的改善工作。'],['我的工作',['对 NIST、libuv 等开源项目开展 Semgrep AI 降噪对比测试。','完成 Qwen 与 GLM 灰度准确率评测，搭建 Sonar C/C++ 环境进行对标分析。','参与代码审计智能体多轮迭代，分析 DeepSeek、GLM、Qwen、GPT 在审计场景下的表现。','持续整理告警分布、性能、降噪率等运营数据，输出分析报告。']],['研究与交付','产出 AI Coding 安全调研、AI 工具治理建议、误报与漏报分析，以及常态化运营报告。评估围绕具体项目、版本和样本开展。'],['判断原则','明确告警主张，核对实际代码与运行前提，记录支持与反对证据。对于证据不足的结论，保留边界，避免把模型表述当成事实。']],note:'本站展示评估工作的方法与范围，不虚构模型评分、降噪率或测试排名。'}};
const dialog=$('#project-dialog');let lastFocus=null;let closingFromHistory=false;
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function openProject(id,push=true){const p=projects[id];if(!p)return;closeMenu();lastFocus=document.activeElement;$('#dialog-content').innerHTML=`<span class="dialog-tags">${p.tag}</span><h2 id="dialog-title">${p.title}</h2><p>${p.intro}</p><div class="case-result">${p.metrics.map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('')}</div>${p.sections.map(([h,t])=>`<h3>${h}</h3>${Array.isArray(t)?`<ul>${t.map(x=>`<li>${x}</li>`).join('')}</ul>`:`<p>${t}</p>`}`).join('')}<p class="case-note">${p.note}</p><div class="dialog-end"><button class="pill dark" id="copy-case">复制项目链接 ↗</button><a href="mailto:ziming-Huang@outlook.com" class="text-link">与我交流这个项目 ↗</a></div>`;if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');dialog.scrollTop=0;if(push){const u=new URL(location.href);u.searchParams.set('project',id);history.pushState({project:id},'',u);}$('#copy-case').addEventListener('click',()=>copy(location.href,'项目链接已复制'));}
$$('[data-project]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openProject(a.dataset.project);}));
$('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(!closingFromHistory){const u=new URL(location.href);u.searchParams.delete('project');history.replaceState({},'',u);}closingFromHistory=false;lastFocus?.focus();});
window.addEventListener('popstate',()=>{const id=new URL(location.href).searchParams.get('project');if(projects[id])openProject(id,false);else if(dialog.open){closingFromHistory=true;dialog.close();}});
const initialProject=new URL(location.href).searchParams.get('project');if(projects[initialProject])openProject(initialProject,false);
const steps=[
 {title:'发现入口，保留上下文。',copy:'扫描器识别到一个由输入路径参与的文件读取操作。先记录输入来源、调用位置与已有约束，形成待验证的告警。',file:'file_reader.py',status:'01 / 待验证',code:'requested = request.args["path"]\n\n# 用户输入参与路径拼接\npath = ROOT / requested\nreturn path.read_text()',note:'需要进一步确认：是否存在路径边界检查？'},
 {title:'用证据，确认真正的风险。',copy:'沿调用链检查输入校验、目录约束和异常处理。这个预设案例中没有路径边界检查，因此继续评估目录逃逸风险。',file:'audit_notes.txt',status:'02 / 核对证据',code:'[✓] 输入来源：外部请求\n[✓] 敏感操作：文件读取\n[×] 目录约束：未发现\n[→] 结论：需要补充路径边界检查',note:'示例结论仅针对这里展示的前提，不代表所有文件读取告警都成立。'},
 {title:'修复边界，而不只是告警。',copy:'解析规范路径，并验证目标仍在允许的根目录内。实际项目中还需结合符号链接、文件权限和并发场景进行验证。',file:'file_reader.py · proposed',status:'03 / 修复建议',code:'root = ROOT.resolve()\npath = (root / requested).resolve()\n\nif not path.is_relative_to(root):\n    raise PermissionError("Outside root")\nreturn path.read_text()',note:'Python 示例：展示路径约束思路，不构成完整文件服务实现。'},
 {title:'让经验，进入下一次编码。',copy:'把问题的输入来源、风险前提、修复方式和验证要点整理为规则，让安全编码阶段就能识别同类风险。',file:'secure_coding_rule.md',status:'04 / 规则沉淀',code:'RULE / FILE PATH BOUNDARY\n\n- 规范化用户输入路径\n- 校验解析后的目录归属\n- 覆盖正常与越界输入\n- 检查链接与权限边界',note:'扫描 → 审计 → 修复 → 预防。每一步都需要可检查的依据。'}];
let step=0;function setStep(n,focus=false){step=n;$$('[data-step]').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===n));b.tabIndex=i===n?0:-1;if(focus&&i===n)b.focus();});const s=steps[n];$('#process-panel').setAttribute('aria-labelledby','step-'+n);$('#process-title').textContent=s.title;$('#process-copy').textContent=s.copy;$('#code-filename').textContent=s.file;$('#process-status').textContent=s.status;$('#process-code').textContent=s.code;$('#process-note').textContent=s.note;$('#process-next').innerHTML=n===3?'重新查看 <span>↺</span>':'下一环节 <span>→</span>';}
$$('[data-step]').forEach(b=>{b.addEventListener('click',()=>setStep(+b.dataset.step));b.addEventListener('keydown',e=>{let n=step;if(e.key==='ArrowRight')n=(step+1)%4;else if(e.key==='ArrowLeft')n=(step+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();setStep(n,true);});});$('#process-next').addEventListener('click',()=>setStep((step+1)%4));
$$('[data-grade]').forEach(b=>b.addEventListener('click',()=>{$('.film-frame').dataset.grade=b.dataset.grade;$$('[data-grade]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#film-label').textContent={cobalt:'COBALT / 原始调色',mono:'NOIR / 黑白',warm:'AMBER / 暖调'}[b.dataset.grade];}));
$('#matrix-art').innerHTML=Array.from({length:80},()=>'<span></span>').join('');
const signal=$('#signal-art');const ctx=signal.getContext('2d');let signalVisible=false;new IntersectionObserver(entries=>{signalVisible=entries[0].isIntersecting;}).observe(signal);
function signalPlot(t){if(signalVisible&&ctx){const r=signal.getBoundingClientRect();if(signal.width!==Math.round(r.width*2)){signal.width=Math.round(r.width*2);signal.height=330;}const w=signal.width,h=signal.height;ctx.clearRect(0,0,w,h);const time=reducedMotion?0:t*.00035;for(let j=0;j<7;j++){ctx.beginPath();ctx.strokeStyle=`rgba(41,72,49,${.2+j*.09})`;ctx.lineWidth=1.4;for(let x=0;x<w;x+=3){const amp=(h*.1)*Math.sin(x/w*Math.PI);const y=h*.5+Math.sin(x*.015+time+j*.25)*amp*(1+j*.2)+(j-3)*9;x===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();}for(let j=0;j<9;j++){const x=(j+.5)*w/9;ctx.fillStyle='#3c623f';ctx.fillRect(x,h*.5+Math.sin(x*.015+time)*h*.1-2,4,4);}}requestAnimationFrame(signalPlot);}requestAnimationFrame(signalPlot);
let viewMode='solid';let sceneController=null;
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{viewMode=b.dataset.view;$$('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));sceneController?.setMode(viewMode);}));
import('./scene.js').then(({startScene})=>{sceneController=startScene({reducedMotion});sceneController.setMode(viewMode);}).catch(()=>{$('#scene-fallback').hidden=false;$('.view-switch').hidden=true;$('.scene-caption').hidden=true;$('.drag-hint').textContent='SIGNAL HOUSE';});
